version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mogab
      - MONGO_INITDB_ROOT_PASSWORD=1994
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    env_file: 
      - .env
    depends_on:
      - mongodb
      - redis

volumes:
  mongo-data:
