services:
  - name: mongodb
    type: docker
    env:
      - MONGO_INITDB_ROOT_USERNAME=mogab
      - MONGO_INITDB_ROOT_PASSWORD=1994
    containers:
      - name: mongodb
        image: mongo:latest
        ports:
          - 27017:27017
        volumes:
          - name: mongo-data
            path: /data/db

  - name: redis
    type: docker
    containers:
      - name: redis
        image: redis:latest
        ports:
          - 6379:6379

  - name: backend
    type: docker
    containers:
      - name: backend
        build:
          dockerfile: Dockerfile
        ports:
          - 5000:5000
        envVars:
          - key: ENVIRONMENT
            value: production
        dependsOn:
          - mongodb
          - redis

volumes:
  - name: mongo-data
    mountPath: /data/db
